### ISSUE TITLE
Human pawn wearing Archon armour makes portrait unable to render

### ISSUE THREAD

**Issue by mfukar** [Ogliss/AdMech-Xeno-AHR-Eldar#1]
Steps to reproduce:
- Create new colony & pawn
- Spawn archon armour and helmet
- Force pawn to wear them

Observed behaviour: Pawn portrait does not render
Expected behaviour: Pawn portrait visible (even partially)

Mod list:
Core (-ideology -royalty)
Harmony
HugsLib
EdB Prepare Carefully
Pick Up And Haul
Rimsenal - Rimhair
Humanoid Alien Races
Adeptus Xenobiologis: Aeldari
RimHUD

Logs (errors): https://gist.github.com/mfukar/73a312d3fecb7f61c683028f73180edf

**Comment by Ogliss** [comment]
Archon armour is supposed to be restricted to Dark Eldar only, it doesnt support vanilla humans, looks like you had a pawn with the hulk body try to equip it
